#' Protein feature detection
#' @description Run the sliding window algorithm to find protein features.
#' @param traces An object of type \code{traces}.
#' @param calibration A list of the calibration functions as generated by \code{calibrateSECMW}.
#' @param corr_cutoff The correlation value for chromatograms above which
#'        peptides are considered to be coeluting, default=0.95.
#' @param window_size numeric size of the window, default=15
#' @param parallelized logical, if the computation should be done in parallel, default=FALSE
#' @param n_cores The number of cores to use for parallel processing, default=1
#' @param collapse_method Method for collapsing multiple features into one feature: "apex_only" or "apex_network", default="apex_only"
#' @param perturb_cutoff The quantile to use in estimating the perturbation level, default="5%".
#'        Intensity values that are zero are replaced with random values that are
#'        below the specified quantile of the input values. Alternatively a
#'        cutoff value can be specified as an upper limit for perturbation values.
#'        This is nescessary for correlation calculation.
#' @param rt_height numeric RT cutoff for collapsing features, default is 5
#' @param smoothing_length numeric smoothing length of Savitzky-Golay filter, default is 11
#' @return A data.table containing protein features.
#' @export

findProteinFeatures <- function(traces,
                                calibration,
                                corr_cutoff=0.95,
                                window_size=15,
                                parallelized=FALSE,
                                n_cores=1,
                                collapse_method="apex_only",
                                perturb_cutoff= "5%",
                                rt_height=5,
                                smoothing_length=11){
  protein.peptide.association.table <- as.data.table(as.data.frame(traces[["trace_annotation"]]))
  setorder(protein.peptide.association.table, "protein_id")
  setnames(protein.peptide.association.table, "protein_id", "complex_id")
  setnames(protein.peptide.association.table, "id", "protein_id")
  protein.peptide.association.table[, complex_name:=complex_id]
  protein.peptide.association.table <- subset(protein.peptide.association.table,select=c("complex_id","complex_name","protein_id"))
  #protein.peptide.association.table

  ProteinFeatures <- findComplexFeatures(traces = traces,
                                         complex_hypothesis = protein.peptide.association.table,
                                         calibration = calibration,
                                         corr_cutoff = corr_cutoff,
                                         window_size = window_size,
                                         parallelized = parallelized,
                                         n_cores=n_cores,
                                         collapse_method=collapse_method,
                                         perturb_cutoff=perturb_cutoff,
                                         rt_height=rt_height,
                                         smoothing_length=smoothing_length)

  fun <- function(x) {strsplit(x,split=";")[[1]][1]}
  ProteinFeatures$monomer_mw <- as.numeric(unlist(lapply(ProteinFeatures$monomer_mw,fun)))
  ProteinFeatures$monomer_sec <- as.numeric(unlist(lapply(ProteinFeatures$monomer_sec,fun)))
  names(ProteinFeatures) <- gsub("complex","protein",names(ProteinFeatures))

  ProteinFeatures <- subset(ProteinFeatures,select=c("protein_id","protein_name","subunits_annotated","n_subunits_annotated","subunits_detected","n_subunits_detected","completeness","left_pp","right_pp","apex","apex_mw","area","peak_corr","monomer_sec","monomer_mw"))
  ProteinFeatures[,monomer_mw_max := 2*ProteinFeatures$monomer_mw]
  ProteinFeatures[,monomer_sec_max := calibration$MWtoSECfraction(monomer_mw_max)]
  ProteinFeatures[,in_complex := FALSE]
  ProteinFeatures$in_complex[ProteinFeatures$apex_mw > 2*ProteinFeatures$monomer_mw] = TRUE

  ProteinFeatures
}
