
#' Import peptide/protein profiles from a Quantitative PCP matrix.
#' @description This function takes a quantitative matrix of peptide/protein intensities
#' generated by a typical PCP experiment and coerces it into the internal PCProfiler input_data structure.
#' @import data.table
#' @param input_data Quantitative MS input_data in form of a data.table. The table can be in long or
#' wide format and has several required columns (see also examplePCPdataWide or examplePCPdataLong).
#' Required columns are: protein_id, filename and intensity for long tables and protein_id for wide tables.
#' @param annotation_table file or data.table containing columns `filename` and
#'     `fraction_number` that map the file names (occuring in input table filename column)
#'     `to a SEC elution fraction.
#' @param rm_decoys boolean, Whether decoys should be removed
#'  (decoys are found by greping "DECOY" in the protein_id column), defaults to FALSE.
#' @return An object of class traces containing
#'     "traces", "traces_type", "traces_annotation" and "fraction_annotation" list entries
#'     that can be processed with the herein contained functions.
#' @examples 
#' pcpData <- examplePCPdataWide
#' ## or
#' pcpData <- examplePCPdataLong
#' annotation <- exampleFractionAnnotation
#' 
#'traces <- importPCPdata(input_data = pcpDataprotWide,
#'                        annotation_table = annotation)
#'
#'summary(traces)
#' @export


importPCPdata <- function(input_data,
                          annotation_table,
                          rm_decoys = FALSE){
  
  ## test arguments
  if (missing(input_data)){
    stop("Need to specify input_data in form of OpenSWATH result file or R data.table.")
  }
  if (missing(annotation_table)){
    stop("Need to specify annotation_table.")
  }
  
  ## read input_data & annotation table
  ##################################################
  
  if (class(input_data)[1] == "character") {
    if (file.exists(input_data)) {
      message('reading results file ...')
      input_data  <- data.table::fread(input_data, sep="\t", header=TRUE)
    } else {
      stop("input_data file doesn't exist")
    }
  } else if (all(class(input_data) != c("data.table","data.frame"))) {
    stop("input_data input is neither file name or data.table")
  }
  
  if (class(annotation_table)[1] == "character") {
    if (file.exists(annotation_table)) {
      message('reading annotation table ...')
      annotation_table  <- data.table::fread(annotation_table)
    } else {
      stop("annotation_table file doesn't exist")
    }
  } else if (all(class(annotation_table) != c("data.table","input_data.frame"))) {
    stop("annotation_table input is neither file name or data.table")
  }
  
  ## Check input for completeness 
  if(!("protein_id" %in% names(input_data))) stop("Missing or wrong comumn names")
  
  if (rm_decoys == TRUE){
    message('removing decoys ...')
    input_data <- input_data[grep("DECOY", input_data$protein_id, invert = T)]
  }
  
  ## Check if table is in long format
  if(any(names(input_data) == "intensity")){
    
    ## add fraction number column to main dataframe
    fraction_number <- integer(length=nrow(input_data))
    files <- annotation_table$filename
    input_dataFilenames <- input_data$filename
    
    if (length(files) != length(unique(input_dataFilenames))) {
      stop("Number of file names in annotation_table does not match data")
    }
    for (i in seq_along(files)){
      idxs <- grep(files[i], input_dataFilenames)
      fraction_number[idxs] <- annotation_table$fraction_number[i]
      # message(paste("PROCESSED", i, "/", length(files), "filenames"))
    }
    input_data <- cbind(input_data, fraction_number)
    
    ## Detect if long  quantMatrix is peptide or protein intensities
    if("peptide_id" %in% names(input_data)){
      
      input_dataWide <- data.table(dcast(input_data, protein_id + peptide_id ~ fraction_number,
                              value.var="intensity", fill = 0))
      ## Make sure fractions are in ascending order
      setcolorder(input_dataWide, c("peptide_id", "protein_id", sort(unique(fraction_number))))
      
    }else{
      
      input_dataWide <- data.table(dcast(input_data, protein_id ~ fraction_number,
                              value.var="intensity", fill = 0))
      setcolorder(input_dataWide, c("protein_id", sort(unique(fraction_number))))
      
    }
    
  }else{
    
    ## if wide data add fraction number as column names
    input_dataFilenames <- names(input_data)[!(names(input_data) %in% c("peptide_id", "protein_id"))]
    fraction_number <- integer(length=length(input_dataFilenames))
    files <- annotation_table$filename
    
    if (length(files) != length(unique(input_dataFilenames))) {
      stop("Number of file names in annotation_table does not match data")
    }
    for (i in seq_along(files)){
      idxs <- grep(files[i], input_dataFilenames)
      fraction_number[idxs] <- annotation_table$fraction_number[i]
      # message(paste("PROCESSED", i, "/", length(files), "filenames"))
    }
    names(input_data)[!(names(input_data) %in% c("peptide_id", "protein_id"))] <- fraction_number
    input_dataWide <- input_data
  }
  
  
  if("peptide_id" %in% names(input_data)){
    ## Check for duplications
    if(any(duplicated(input_dataWide[, .(protein_id, peptide_id)]))){
      stop("The input data contains duplicated  intensity values (maybe. from different peptides?).
           Please make sure you provide unique protein_id, peptide_id filename combinations")
      
    }
    setcolorder(input_dataWide, c("peptide_id", "protein_id", sort(unique(fraction_number))))
    traces_annotation <- data.table(input_dataWide[,c("peptide_id", "protein_id"), with = FALSE])
    setnames(traces_annotation,c("peptide_id", "protein_id"),c("id","protein_id"))
    traces_type <- "peptide"
    traces <- subset(input_dataWide, select = -protein_id)
    traces[,id:=peptide_id]
    traces[,peptide_id:=NULL]

  }else{
    ## check if there are duplicated protein entries (e.g. from different charge states)
    if(any(duplicated(input_dataWide$protein_id))){
      stop("The input data contains duplicated protein intensity values (maybe. from different peptides?).
           Please make sure you provide unique protein_id, filename combinations")
    }
    
    setcolorder(input_dataWide, c("protein_id", sort(unique(fraction_number))))
    traces_annotation <- data.table(input_dataWide[,.(protein_id)])
    setnames(traces_annotation,"protein_id", "id")
    traces_type <- "protein"
    traces <- input_dataWide
    traces[,id:=protein_id]
    traces[,protein_id:=NULL]
    
  }
  
  
  ## Produce the traces object
  
  fraction_annotation = annotation_table
  names(fraction_annotation) <- c("filename", "id")

  result <- list("traces" = traces,
                 "trace_type" = traces_type,
                 "trace_annotation" = traces_annotation,
                 "fraction_annotation" = fraction_annotation)
  class(result) <- "traces"
  return(result)
  
}
  
 