#' Quantify proteins based on topN peptides from peptide level traces.
#' @description Quantify proteins based on topN peptides from peptide level traces
#' summing top N highest cumulative intensity peptides. $traces and $trace_annotation
#'  are collapsed to protein level. trace$id content switches from peptide_ids to protein_ids.
#' @import reshape
#' @import data.table
#' @param Traces peptide level traces object as generated by import and upstream filtering functions.
#' @param topN integer number of highest intensity peptides to use for quantification.
#' The ID of the peptides used is maintained in the $trace_annotation table of the output
#' protein level traces object.
#' @param keep_less logical, whether proteins with less than topN peptides shall be 
#' kept (TRUE) or discarded (FALSE). Defaults to FALSE to enable label-free intensity comparisons
#' following the best-flyer hypothesis.
#' @param remove.decoys logical, whether to remove decoys
#' @return Traces of $trace_type = "protein".
#' @export

proteinQuantification <- function(Traces, topN = 2, keep_less = FALSE, remove.decoys = TRUE){
  # Check if it's a peptide level table
  if(Traces$trace_type != "peptide"){
    stop("The input object is not a peptide level traces object but", Traces$trace_type)
  }
  
  #remove decoys
  if (remove.decoys) {
    idx_decoys <- grep("^DECOY_",Traces$trace_annotation$protein_id)
    Traces$traces <- Traces$traces[-idx_decoys]
    Traces$trace_annotation<- Traces$trace_annotation[-idx_decoys]
  }
  
  # Extract wide table for calculations
  peptideTracesTable <- data.table(protein_id = Traces$trace_annotation$protein_id,
                                   peptide_id = Traces$trace_annotation$id,
                                   subset(Traces$traces, select =-id))
  
  # Calculations in long format - sum the topN peptides per protein
  peptideTraces.long <- melt(peptideTracesTable,
                             id.vars = c("protein_id", "peptide_id"),
                             variable.name = "fraction_number",
                             value.name = "intensity")
  peptideTraces.long[, intensity:=as.numeric(intensity)]
  peptideTraces.long[, peptide_intensity:=sum(intensity), peptide_id]
  peptideTraces.long[, n_peptides:=length(unique(peptide_id)), protein_id]
  # the ties.method makes sure how to deal with peptides of identical intensity: "first" keeps the order of occurence 
  peptideTraces.long[, peptide_rank:=rank(-peptide_intensity[1:n_peptides[1]],ties.method = "first"), protein_id]
  peptideTraces.long <- peptideTraces.long[peptide_rank <= topN]
  # collect information which peptides were used for quantification
  peptideTraces.long[, quant_peptides_used:=paste(unique(peptide_id), collapse = ","), protein_id]
  
  # if not wanted, kick out those with less than N peptides
  if(!keep_less){
    peptideTraces.long <- peptideTraces.long[n_peptides >= topN]
  }
  
  # Sum peptides to protein level (wide) traces table
  peptideTraces.topNsum.wide <- as.data.table(cast(peptideTraces.long,
                                     protein_id ~ fraction_number,
                                     value = "intensity",
                                     fun.aggregate = sum))
  # move id column to end to ensure correct quant value index
  peptideTraces.topNsum.wide[, id:=protein_id]
  peptideTraces.topNsum.wide <- subset(peptideTraces.topNsum.wide, select=-protein_id)
  
  ## assemble updated, protein-level trace_annotation table
  peptideTraces.topNsum.wide.annotation <- merge(subset(Traces$trace_annotation, select =-id),
                                                 unique(peptideTraces.long[,.(protein_id, n_peptides, quant_peptides_used)]),
                                                 by = "protein_id", all.x = FALSE, all.y = TRUE)
  peptideTraces.topNsum.wide.annotation <- unique(peptideTraces.topNsum.wide.annotation)
  peptideTraces.topNsum.wide.annotation[, id:=protein_id]

  if (!all(peptideTraces.topNsum.wide.annotation$id == peptideTraces.topNsum.wide$id)){
    stop("traces$id != trace_annotation$id")
  }
  
  # assemble result protein level traces object
  Traces$traces <- peptideTraces.topNsum.wide
  Traces$trace_annotation <- peptideTraces.topNsum.wide.annotation
  Traces$trace_type <- "protein"
  return(Traces)
}