#' Resolve protein features based on annotated proteoforms
#' @param features Protein features as generated by \code{findProteinFeatures}.
#' @param traces Object of class traces. 
#' @param minProteoformIntensityRatio Value between 0 and 1. Default = 0.1.
#' @param perturb_cutoff percentage. Default = "5%".
#' @return Protein features resolved by proteoforms.
#' @export
resolveProteoformSpecificFeatures <- function(features, 
                                              traces, 
                                              minProteoformIntensityRatio=0.1, 
                                              perturb_cutoff="5%"){
  
  traceMat <- getIntensityMatrix(traces)
  # Impute noise for missing intensity measurements globally for all traces
  traceMatImputed <- copy(traceMat)
  nZero <- sum(traceMatImputed == 0) # number of ZERO values in matrix
  measuredVals <- traceMatImputed[traceMatImputed != 0]
  if(class(perturb_cutoff) == "character"){
    qt <- as.numeric(gsub("%","",perturb_cutoff))/100
    perturb_cutoff <- quantile(measuredVals, qt)
  }
  set.seed(123) # set seed to always get same results
  traceMatImputed[traceMatImputed == 0] <- runif(min = 0, max = perturb_cutoff, nZero)
  
  idx <- seq_len(nrow(features))
  res <- lapply(idx, function(i){
    print(i)
    x <- features[i,]
    if (length(grep("DECOY",x$protein_id)) == 0) {
      peptides_detected <- unlist(strsplit(x$subunits_detected, split = ";"))
      traces_sub <- subset(traces$trace_annotation,id %in% peptides_detected)
      proteoforms_detected <- sort(unique(traces_sub$proteoform_id))
      if (length(proteoforms_detected) > 1) {
        maxPeptideSumPerProteoform <- lapply(proteoforms_detected, function(p){
          traces_sub_sub <- subset(traces, p, trace_subset_type = "proteoform_id")
          traces_sub_sub <- subset(traces_sub_sub, peptides_detected)
          #traceMat <- getIntensityMatrix(traces_sub_sub)
          #tracesFeature <- traceMat[,x$left_pp:x$right_pp]
          peptides_in_proteoform <- traces_sub_sub$trace_annotation$id
          #tracesFeature <- traceMatImputed[peptides_in_proteoform,x$left_pp:x$right_pp]
          #if (is.matrix(tracesFeature)) {
          #  tracesSum <- rowSums(tracesFeature)
          #} else {
          #  tracesSum <- sum(tracesFeature)
          #}
          tracesSum <- traceMatImputed[peptides_in_proteoform,x$apex]
          max(tracesSum)
        })
        names(maxPeptideSumPerProteoform) <- proteoforms_detected
        # remove features from empty traces
        #if (all(maxPeptideSumPerProteoform == 0)) {
        #  return(NULL)
        #}
        intensityRatioPerProteoform <- lapply(maxPeptideSumPerProteoform, 
                                              function(x){x/max(unlist(maxPeptideSumPerProteoform))})
        proteoforms_detected <- proteoforms_detected[which(intensityRatioPerProteoform >= minProteoformIntensityRatio)]
        peptides_detected <- unique(subset(traces_sub,proteoform_id %in% proteoforms_detected)$id)
      }
      proteoform_subunits_annotated <- unique(subset(traces$trace_annotation, 
                                                     proteoform_id %in% proteoforms_detected)$id)
      #featureTraces <- subset(traces, proteoform_subunits_annotated)
      #featureMatrix <- getIntensityMatrix(featureTraces)
      featureMatrix <- traceMatImputed[peptides_detected,x$left_pp:x$right_pp]
      #if (all(featureMatrix == 0)) {
      #  return(NULL)
      #}
    } else {
      peptides_detected <- unlist(strsplit(x$subunits_detected, split = ";"))
      traces_sub <- subset(traces$trace_annotation,id %in% peptides_detected)
      
      target_protein <- gsub("DECOY_","",x$protein_id)
      target_traces <- subset(traces, target_protein, trace_subset_type = "protein_id")
      all_target_proteoforms <- target_traces$trace_annotation$proteoform_id
      decoy_peptides_annotated <- unlist(strsplit(x$subunits_annotated, split = ";"))
      which_decoy_peptides_detected <- which(decoy_peptides_annotated %in% peptides_detected)
      proteoforms_detected_all <- all_target_proteoforms[which_decoy_peptides_detected]
      proteoforms_detected <- unique(proteoforms_detected_all)
      
      if (length(proteoforms_detected) > 1) {
        maxPeptideSumPerProteoform <- lapply(proteoforms_detected, function(p){
          which_decoy_peptides_inProteoform <- which(proteoforms_detected_all==p)
          traces_sub_sub <- subset(traces, peptides_detected[which_decoy_peptides_inProteoform])
          peptides_in_proteoform <- traces_sub_sub$trace_annotation$id
          #tracesFeature <- traceMatImputed[peptides_in_proteoform,x$left_pp:x$right_pp]
          #if (is.matrix(tracesFeature)) {
          #  tracesSum <- rowSums(tracesFeature)
          #} else {
          #  tracesSum <- sum(tracesFeature)
          #}
          tracesSum <- traceMatImputed[peptides_in_proteoform,x$apex]
          max(tracesSum)
        })
        names(maxPeptideSumPerProteoform) <- proteoforms_detected
        intensityRatioPerProteoform <- lapply(maxPeptideSumPerProteoform, 
                                              function(x){x/max(unlist(maxPeptideSumPerProteoform))})
        proteoforms_detected <- proteoforms_detected[which(intensityRatioPerProteoform >= minProteoformIntensityRatio)]
        peptides_detected <- peptides_detected[which(proteoforms_detected_all %in% proteoforms_detected)]
      }
      proteoform_subunits_annotated <- decoy_peptides_annotated[which(all_target_proteoforms %in% proteoforms_detected)]
      featureMatrix <- traceMatImputed[peptides_detected,x$left_pp:x$right_pp]
    }
    corrN <-cor(t(featureMatrix))
    diag(corrN) <- NA
    correlationN <- mean(corrN[upper.tri(corrN)], na.rm=T)
    areaN <- sum(featureMatrix)
    completenessN <- length(peptides_detected)/length(proteoform_subunits_annotated)
    report <- copy(x)
    report$subunits_annotated <- paste(proteoform_subunits_annotated,collapse = ";")
    report$n_subunits_annotated <- length(proteoform_subunits_annotated)
    report$subunits_detected <- paste(peptides_detected,collapse = ";")
    report$n_subunits_detected <- length(peptides_detected)
    report$completeness <- completenessN
    report$area <- areaN
    report$peak_corr <- correlationN
    report[,proteoform_ids := paste(proteoforms_detected, collapse = ";")]
    report[,n_proteoform_ids := length(proteoforms_detected)]
    return(report)
  })
  combiRes <- do.call(rbind,res)
  return(combiRes)
}
