#' Resolve protein features based on annotated proteoforms
#' @param features Protein features as generated by \code{findProteinFeatures}.
#' @param traces Object of class traces. 
#' @param minProteoformIntensityRatio Value between 0 and 1. Default = 0.1.
#' @param perturb_cutoff percentage. Default = "5%".
#' @return Protein features resolved by proteoforms.
#' @export
resolveProteoformSpecificFeatures <- function(features, 
                                              traces, 
                                              minProteoformIntensityRatio=0.1, 
                                              perturb_cutoff="5%"){
  
  traceMat <- getIntensityMatrix(traces)
  # Impute noise for missing intensity measurements globally for all traces
  traceMatImputed <- copy(traceMat)
  nZero <- sum(traceMatImputed == 0) # number of ZERO values in matrix
  measuredVals <- traceMatImputed[traceMatImputed != 0]
  if(class(perturb_cutoff) == "character"){
    qt <- as.numeric(gsub("%","",perturb_cutoff))/100
    perturb_cutoff <- quantile(measuredVals, qt)
  }
  set.seed(123) # set seed to always get same results
  traceMatImputed[traceMatImputed == 0] <- runif(min = 0, max = perturb_cutoff, nZero)
  
  idx <- seq_len(nrow(features))
  res <- lapply(idx, function(i){
    print(i)
    x <- features[i,]
    if (length(grep("DECOY",x$protein_id)) == 0) {
      peptides_detected <- unlist(strsplit(x$subunits_detected, split = ";"))
      traces_sub <- subset(traces$trace_annotation,id %in% peptides_detected)
      proteoforms_detected <- sort(unique(traces_sub$proteoform_id))
      if (length(proteoforms_detected) > 1) {
        maxPeptideSumPerProteoform <- lapply(proteoforms_detected, function(p){
          traces_sub_sub <- subset(traces, p, trace_subset_type = "proteoform_id")
          traces_sub_sub <- subset(traces_sub_sub, peptides_detected)
          #traceMat <- getIntensityMatrix(traces_sub_sub)
          #tracesFeature <- traceMat[,x$left_pp:x$right_pp]
          peptides_in_proteoform <- traces_sub_sub$trace_annotation$id
          #tracesFeature <- traceMatImputed[peptides_in_proteoform,x$left_pp:x$right_pp]
          #if (is.matrix(tracesFeature)) {
          #  tracesSum <- rowSums(tracesFeature)
          #} else {
          #  tracesSum <- sum(tracesFeature)
          #}
          tracesSum <- traceMatImputed[peptides_in_proteoform,x$apex]
          max(tracesSum)
        })
        names(maxPeptideSumPerProteoform) <- proteoforms_detected
        # remove features from empty traces
        #if (all(maxPeptideSumPerProteoform == 0)) {
        #  return(NULL)
        #}
        intensityRatioPerProteoform <- lapply(maxPeptideSumPerProteoform, 
                                              function(x){x/max(unlist(maxPeptideSumPerProteoform))})
        proteoforms_detected <- proteoforms_detected[which(intensityRatioPerProteoform >= minProteoformIntensityRatio)]
        peptides_detected <- unique(subset(traces_sub,proteoform_id %in% proteoforms_detected)$id)
      }
      proteoform_subunits_annotated <- unique(subset(traces$trace_annotation, 
                                                     proteoform_id %in% proteoforms_detected)$id)
      #featureTraces <- subset(traces, proteoform_subunits_annotated)
      #featureMatrix <- getIntensityMatrix(featureTraces)
      featureMatrix <- traceMatImputed[peptides_detected,x$left_pp:x$right_pp]
      #if (all(featureMatrix == 0)) {
      #  return(NULL)
      #}
    } else {
      peptides_detected <- unlist(strsplit(x$subunits_detected, split = ";"))
      traces_sub <- subset(traces$trace_annotation,id %in% peptides_detected)
      
      target_protein <- gsub("DECOY_","",x$protein_id)
      target_traces <- subset(traces, target_protein, trace_subset_type = "protein_id")
      all_target_proteoforms <- target_traces$trace_annotation$proteoform_id
      decoy_peptides_annotated <- unlist(strsplit(x$subunits_annotated, split = ";"))
      which_decoy_peptides_detected <- which(decoy_peptides_annotated %in% peptides_detected)
      proteoforms_detected_all <- all_target_proteoforms[which_decoy_peptides_detected]
      proteoforms_detected <- unique(proteoforms_detected_all)
      
      if (length(proteoforms_detected) > 1) {
        maxPeptideSumPerProteoform <- lapply(proteoforms_detected, function(p){
          which_decoy_peptides_inProteoform <- which(proteoforms_detected_all==p)
          traces_sub_sub <- subset(traces, peptides_detected[which_decoy_peptides_inProteoform])
          peptides_in_proteoform <- traces_sub_sub$trace_annotation$id
          #tracesFeature <- traceMatImputed[peptides_in_proteoform,x$left_pp:x$right_pp]
          #if (is.matrix(tracesFeature)) {
          #  tracesSum <- rowSums(tracesFeature)
          #} else {
          #  tracesSum <- sum(tracesFeature)
          #}
          tracesSum <- traceMatImputed[peptides_in_proteoform,x$apex]
          max(tracesSum)
        })
        names(maxPeptideSumPerProteoform) <- proteoforms_detected
        intensityRatioPerProteoform <- lapply(maxPeptideSumPerProteoform, 
                                              function(x){x/max(unlist(maxPeptideSumPerProteoform))})
        proteoforms_detected <- proteoforms_detected[which(intensityRatioPerProteoform >= minProteoformIntensityRatio)]
        peptides_detected <- peptides_detected[which(proteoforms_detected_all %in% proteoforms_detected)]
      }
      proteoform_subunits_annotated <- decoy_peptides_annotated[which(all_target_proteoforms %in% proteoforms_detected)]
      featureMatrix <- traceMatImputed[peptides_detected,x$left_pp:x$right_pp]
    }
    corrN <-cor(t(featureMatrix))
    diag(corrN) <- NA
    correlationN <- mean(corrN[upper.tri(corrN)], na.rm=T)
    areaN <- sum(featureMatrix)
    completenessN <- length(peptides_detected)/length(proteoform_subunits_annotated)
    report <- copy(x)
    report$subunits_annotated <- paste(proteoform_subunits_annotated,collapse = ";")
    report$n_subunits_annotated <- length(proteoform_subunits_annotated)
    report$subunits_detected <- paste(peptides_detected,collapse = ";")
    report$n_subunits_detected <- length(peptides_detected)
    report$completeness <- completenessN
    report$area <- areaN
    report$peak_corr <- correlationN
    report[,proteoform_ids := paste(proteoforms_detected, collapse = ";")]
    report[,n_proteoform_ids := length(proteoforms_detected)]
    return(report)
  })
  combiRes <- do.call(rbind,res)
  return(combiRes)
}


#' Refine annotated proteoforms in traces and features based on detected co-elution signals
#' @param traces Object of class traces.
#' @param features Protein features as generated by \code{findProteinFeatures}.
#' @return List containing 1. refined traces and 2. refinded features.
#' @export
refineProteoformsByDetectedFeatures <- function(traces, features) {
  pepToProteoformAssignment <- copy(features)
  subunits <- cSplit(pepToProteoformAssignment, "subunits_annotated", sep = ";", direction = "long")
  subunits[, n_unique_proteoforms := length(unique(proteoform_ids)), by="protein_id"]
  subunits[, proteoform_ids := ifelse(n_unique_proteoforms==1, protein_id, proteoform_ids)]
  subunits[, n_proteoform_ids := length(unlist(strsplit(proteoform_ids, split = ";"))), by="proteoform_ids"]
  #specialProteins <- unique(subunits[n_unique_proteoforms<n_proteoform_ids]$protein_id)
  specialProteins <- unique(subunits[(n_unique_proteoforms > 1)]$protein_id)
  res <- lapply(specialProteins, function(x){
    #print(x)
    data <- subunits[protein_id==x]
    proteoforms <- unique(data$proteoform_ids)
    proteoforms <- strsplit(proteoforms, split = ";")
    names(proteoforms) <- seq_len(length(proteoforms))
    c <- Venn(proteoforms)@IntersectionSets
    c <- c[which(lapply(c,length)>0)]
    conversionTable <- lapply(seq_along(c),function(y){
      tab <- c[[y]]
      tab <- data.table(original_id=tab)
      tab[, new_id := paste0(x,"_",y)]
    })
    conversionTable <- rbindlist(conversionTable)
    data[, proteoform_ids := mgsub::mgsub(string = proteoform_ids,
                                          pattern = conversionTable$original_id,
                                          replacement = conversionTable$new_id)]
    data[, proteoform_ids := paste(sort(unique(unlist(strsplit(proteoform_ids, split = ";")))), 
                                   collapse = ";"), by="proteoform_ids"]
    return(list(data, conversionTable))
  })
  specialProteins_res <- rbindlist(lapply(res, `[[`, 1))
  subunits <- subset(subunits, ! protein_id %in% specialProteins)
  subunits_final <- rbind(subunits, specialProteins_res)
  subunits_final[, n_unique_proteoforms := length(unique(proteoform_ids)), by="protein_id"]
  subunits_final[, proteoform_ids := ifelse(n_unique_proteoforms==1, protein_id, proteoform_ids)]
  subunits_final[, n_proteoform_ids := length(unlist(strsplit(proteoform_ids, split = ";"))), 
                 by="proteoform_ids"]
  subunits_final[, subunits_annotated_new := paste(subunits_annotated,collapse=";"), 
                 by = c("protein_id", "subunits_detected","completeness", 
                        "apex", "area", "peak_corr", "coelution_score", "qvalue")]
  subunits_final[, subunits_annotated := subunits_annotated_new]
  subunits_final[, subunits_annotated_new := NULL]
  subunits_final <- unique(subunits_final)
  
  traces_new <- copy(traces)
  conversionTable <- rbindlist(lapply(res, `[[`, 2))
  traces_new$trace_annotation <- merge(traces_new$trace_annotation, conversionTable, 
                                       by.x="proteoform_id", by.y="original_id", all = TRUE, sort = FALSE)
  traces_new$trace_annotation[, new_id := ifelse((is.na(new_id)) & (n_proteoforms==1), proteoform_id, new_id)]
  assigned_ids <- unique(traces_new$trace_annotation$new_id)
  assigned_ids <- assigned_ids[! is.na(assigned_ids)]
  traces_new <- subset(traces_new, assigned_ids, trace_subset_type = "new_id")
  traces_new$trace_annotation[, proteoform_id := NULL]
  setnames(traces_new$trace_annotation, "new_id", "proteoform_id") 
  traces_new$trace_annotation[, cluster := as.integer(ifelse(length(grep("_",proteoform_id))>0,
                                                             gsub(".*_","",proteoform_id),"1")), 
                              by=c("protein_id","id")]
  traces_new$trace_annotation[, n_proteoforms_beforeReassignment := n_proteoforms]
  traces_new$trace_annotation[, n_proteoforms := length(unique(proteoform_id)), by="protein_id"]
  
  return(list(traces = traces_new, features = subunits_final))
}

